### PR TITLE
fix(logging/config): validates config file action methods

### LINKED ISSUE #478: Silent Failing when inject is misspelled.
When the action is typoed (in my case I did injest not inject) it silently failed and defaulted to save

```javascript
  /**
     * With "inject" you need to set up one of the below clients.
     * Options: "save", "inject"
     */
    action: "injest",
    /**
``` 
vs 

```javascript
  /**
     * With "inject" you need to set up one of the below clients.
     * Options: "save", "inject"
     */
    action: "inject",
    /**
```

### PR DESCRIPTION
**Pull request by zakkarry**
will not silently proceed to save if erroneous values are set for action in the config file.

- Fixes #478

### CODE REVIEW

File: src/torrent.ts [hunk 1]
```diff
@@ -168,6 +168,18 @@ export async function getInfoHashesToExclude(): Promise<string[]> {
 	);
 }
 
+export async function validateAction(): Promise<void> {
```
Comment (mmgoodnow) [inline src/torrent.ts:171]: There might be a better home for this file—maybe `action.ts` or somewhere else we have a lot of validation code?

**Review by mmgoodnow — COMMENTED** [review]
this feels like a somewhat narrow fix. Yes it fixes when someone misspells `action` but they could also misspell `matchMode`, or makes `dataDirs` a string instead of a string[], etc. 

I think something like using [`zod`](https://zod.dev) in a function like `validateConfig` could be a more holistic approach.

File: src/torrent.ts (hunk 1 above)
Comment (zakkarry) [reply src/torrent.ts]: Moved to action.ts
