### PR TITLE
fix(torrentDir): support torrentDir without client if action save

### LINKED ISSUE #890: Fails to start since v6.8.10 - Indexing failed (0): Cannot read properties of null (reading 'getAllDownloadDirs')
### What's happening surrounding the bug? (context)

Starting with v6.8.10 (also tested on latest, v6.9.1), my cross-seed container stopped working.

### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [x] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [x] I've tried to solve this already

### Reproducing the bug

Update from v6.8.9 to v6.8.10 or later.

### What should be happening?

It should start (or tell me, if I need to update my config).

On 6.8.9, it runs correctly:
```
Configuration file already exists.
2025-01-21 14:43:04 info: cross-seed v6.8.9
2025-01-21 14:43:04 info: Validating your configuration...
2025-01-21 14:43:04 warn: outputDir should only contain .torrent files, cross-seed will populate and manage (https://www.cross-seed.org/docs/basics/options#outputdir)
2025-01-21 14:43:04 error: Indexer http://192.168.155.88:9696/51/api responded with code 404 when fetching caps, check verbose logs
2025-01-21 14:43:04 warn: Indexer http://192.168.155.88:9696/44/api was rate limited when fetching caps
2025-01-21 14:43:04 warn: Indexer http://192.168.155.88:9696/67/api was rate limited when fetching caps
2025-01-21 14:43:04 info: Your configuration is valid!
2025-01-21 14:43:04 info: [server] Server is running on port 2468, ^C to stop.
2025-01-21 14:43:04 info: [scheduler] updateIndexerCaps: last run 13h ago, next run in 11h
2025-01-21 14:43:04 info: [scheduler] cleanup: last run 12h ago, next run in 12h
```

### Your setup

```markdown
- OS: Debian
- Prowlarr: version 1.30.1.4928
- Docker: version 26.0.0, build 2ae903e
```

### config.js (REDACT SENSITIVE INFORMATION)

```
"use strict";
// If you find yourself always using the same command-line flag, you can set
// it here as a default.

Object.defineProperty(exports, "__esModule", { value: true });

const jacket_base_url = "http://192.168.155.88:9117/api/v2.0/indexers";
const jacket_api_key = "...";
const jackett_indexers = [
    "yggtorrent",
];
const getJackettUrl = (indexer) => `${jacket_base_url}/${indexer}/results/torznab/api?apikey=${jacket_api_key}&t=search&cat=&q=`;

const prowlarr_base_url = "http://192.168.155.88:9696";
const prowlarr_api_key = "...";
const prowlarr_indexers = [
    82,
    31,
    61,
    65,
    43,
    33,
    21,
    71,
    24,
    68,
    45,
    63,
    66,
    73,
    53,
    44,
    78,
    60,
    34,
    64,
    54,
    81,
    48,
    67,
    56,
    57,
    72,
    62,
    79,
    51,
    25,
    32,
    76,
    47,
    26,
];
const getProwlarrUrl = (indexer) => `${prowlarr_base_url}/${indexer}/api?apikey=${prowlarr_api_key}`;

module.exports = {
    /**
     * WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING!
     *
     * THE NEXT 8 OPTIONS CONTAIN POTENTIALLY SENSITIVE INFORMATION
     * THERE IS A NOTE WHERE YOU WILL WANT TO START COPYING FROM
     * IF YOU ARE TRYING TO SHARE YOUR CONFIGURATION SETTINGS!
     *
     * WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING!
     **/

    /**
     * Provide your own API key here to override the autogenerated one.
     * Not recommended - prefer using the autogenerated API key via
     * `cross-seed api-key`.
     * Must be 24+ characters.
     */
    apiKey: '...',

    /**
     * List of Torznab URLs.
     * For Jackett, click "Copy RSS feed".
     * For Prowlarr, click on the indexer name and copy the Torznab Url, then
     * append "?apikey=YOUR_PROWLARR_API_KEY". Wrap each URL in quotation marks
     * and separate them with commas, and surround the entire set in brackets.
     */
    torznab: [
        ...jackett_indexers.map(i => getJackettUrl(i)),
        ...prowlarr_indexers.map(i => getProwlarrUrl(i)),
    ],

    /**
     * URL(s) to your Sonarr instance(s), included in the same way as torznab
     * URLs but for your Sonarr: note that api is not at the end. see below.
     *
     * You should order these in most likely to match -> the least likely order.
     * They are searched sequentially as they are listed.
     *
     * This apikey parameter comes from Sonarr
     *
     * Example: sonarr: ["http://sonarr:8989/?apikey=12345"],
     *
     *      sonarr: ["http://sonarr:8989/?apikey=12345",
     *               "http://sonarr4k:8989/?apikey=12345"],
     */
    sonarr: ["http://192.168.155.88:8989/?apikey=..."],

    /**
     * URL(s) to your Radarr instance(s), included in the same way as torznab
     * URLs but for your Radarr: note that api is not at the end. see below.
     *
     * You should order these in most likely to match -> the least likely order.
     * They are searched sequentially as they are listed.
     *
     * This apikey parameter comes from Radarr
     *
     * Example: radarr: ["http://radarr:7878/?apikey=12345"],
     *
     *       radarr: ["http://radarr:7878/?apikey=12345",
     *                "http://radarr4k:7878/?apikey=12345"],
     */
    radarr: ["http://192.168.155.88:7878/?apikey=..."],

    /**
     * Bind to a specific host address.
     * Example: "127.0.0.1"
     * Default is "0.0.0.0"
     */
    host: undefined,

    /**
     * The port you wish to listen on for daemon mode.
     */
    port: 2468,

    /**
     * cross-seed will send POST requests to this url with a JSON payload of
     * { title, body }. Conforms to the caronc/apprise REST API.
     */
    notificationWebhookUrl: undefined,

    /**
     * The url of your rtorrent XMLRPC interface.
     * Only relevant with action: "inject".
     * Could be something like "http://username:password@localhost:1234/RPC2
     */
    rtorrentRpcUrl: undefined,

    /**
     * The url of your qBittorrent webui.
     * Only relevant with action: "inject".
     *
     * If using Automatic Torrent Management, please read:
     * https://www.cross-seed.org/docs/v6-migration#qbittorrent
     *
     * Supply your username and password inside the url like so:
     * "http://username:password@localhost:8080"
     */
    qbittorrentUrl: undefined,

    /**
     * The url of your Transmission RPC interface.
     * Usually ends with "/transmission/rpc".
     * Only relevant with action: "inject".
     * Supply your username and password inside the url like so:
     * "http://username:password@localhost:9091/transmission/rpc"
     */
    transmissionRpcUrl: undefined,

    /**
     * The url of your Deluge JSON-RPC interface.
     * Usually ends with "/json".
     * Only relevant with action: "inject".
     * Supply your WebUI password as well like so:
     * "http://:password@localhost:8112/json"
     */
    delugeRpcUrl: undefined,

    /**
     * END OF POTENTIALLY SENSITIVE CONFIGURATION OPTIONS
     */

    /**
     * Pause at least this many seconds in between each search. Higher is safer
     * for you and friendlier for trackers.
     * Minimum value of 30.
     */
    delay: 30,

    /**
     * To search with downloaded data, you can pass in directories to your downloaded torrent data
     * to find matches rather using the torrent files themselves for matching.
     */
    dataDirs: undefined,

    /**
     * Defines what qBittorrent or Deluge category to set on linked torrents
     *
     * qBittorrent: If you have linking enabled, all torrents will be injected
     * to this category.
     *
     * Default is "cross-seed-link".
     */
    linkCategory: "cross-seed-link",

    /**
     * If this is specified, cross-seed will create links to matched files in
     * the specified directory.
     * It will create a different link for every changed file name or directory
     * structure.
     *
     * Unlike dataDirs, this is just a quoted string WITHOUT []'s around it.
     *
     * If you are a Windows user you need to put double '\' (e.g. "C:\\links")
     *
     * IF YOU ARE USING HARDLINKS, THIS MUST BE UNDER THE SAME VOLUME AS YOUR
     * DATADIRS. THIS PATH MUST ALSO BE ACCESSIBLE VIA YOUR TORRENT CLIENT
     * USING THE SAME PATH.
     *
     * We recommend reading the following FAQ entry:
     * https://www.cross-seed.org/docs/basics/faq-troubleshooting#what-linktype-should-i-use
     */
    linkDir: undefined,

    /**
     * cross-seed will use links of this type to inject data-based matches into your client.
     * Only relevant if dataDirs is specified.
     * Options: "symlink", "hardlink"
     */
    linkType: "symlink",

    /**
     * Enabling this will link files using v5's flat folder style.
     *
     * Each individual Torznab tracker's cross-seeds, otherwise, will have its
     * own folder with the tracker's name and it's links within it.
     *
     * If using Automatic Torrent Management in qBittorrent, please read:
     * https://www.cross-seed.org/docs/v6-migration#qbittorrent
     *
     * Default: false.
     */
    flatLinking: false,

    /**
     * Determines flexibility of naming during matching.
     * "safe" will allow only perfect name/size matches using the standard
     * matching algorithm.
     * "risky" uses filesize as its only comparison point.
     * "partial" is like risky but allows matches if they are missing small
     * files like .nfo/.srt.
     * Options: "safe", "risky", "partial".
     *
     * We recommend reading the following FAQ entry:
     * https://www.cross-seed.org/docs/basics/faq-troubleshooting#what-linktype-should-i-use
     */
    matchMode: "safe",

    /**
     * Determines how deep into the specified dataDirs to go to generate new
     * searchees. Setting this to higher values will result in more searchees
     * and more API hits to your indexers.
     */
    maxDataDepth: 2,

    /**
     * Directory containing torrent files.
     * For rtorrent, this is your session directory
     * as configured in your .rtorrent.rc file.
     * For deluge, this is ~/.config/deluge/state.
     * Don't change this for Docker.
     * Instead set the volume mapping on your docker container.
     */
    torrentDir: "/torrents",

    /**
     * Where to put the torrent files that cross-seed finds for you.
     * Don't change this for Docker.
     * Instead set the volume mapping on your docker container.
     */
    outputDir: "/cross-seeds",

    /**
     * Whether to include single episode torrents in a search (not those from
     * season packs).
     *
     * This setting does not affect matching episodes from rss and
     * announce.
     */
    includeSingleEpisodes: false,

    /**
     * Include torrents which are comprised of non-video files.
     *
     * If this option is set to false, any folders or torrents whose
     * totalNonVideoFilesSize / totalSize > fuzzySizeThreshold
     * will be excluded.
     *
     * For example, if you have .srt or .nfo files inside a torrent, using
     * false will still allow the torrent to be considered for cross-seeding
     * while disallowing torrents that are music, games, books, etc.
     * For full disc based folders (not .ISO) you may wish to set this as true.
     *
     * To search for all video media except individual episodes, use:
     *
     *    includeSingleEpisodes: false
     *    includeNonVideos: false
     *
     * To search for all video media including individual episodes, use:
     *
     *    includeSingleEpisodes: true
     *    includeNonVideos: false
     *
     * To search for absolutely ALL types of content, including non-video, configure
     * your episode settings based on the above examples and use:
     *
     *     includeNonVideos: true
     */
    includeNonVideos: false,

    /**
     * Match season packs from the individual episodes you already have.
     *
     * undefined or null - disabled
     * 1 - must have all episodes
     * 0.8 - must have at least 80% of the episodes
     */
    seasonFromEpisodes: null,

    /**
     * You should NOT modify this unless you have good reason.
     * The following option is the preliminary value to compare sizes of
     * releases for further comparison.
     *
     * decimal value (0.02 = 2%)
     */
    fuzzySizeThreshold: 0.02,

    /**
     * Time based options below use the following format:
     * https://github.com/vercel/ms
     */

    /**
     * Exclude torrents first seen by cross-seed more than this long ago.
     * Examples:
     * "5 days"
     * "2 weeks"
     *
     * This value must be in the range of 2-5 times your excludeRecentSearch
     */
    excludeOlder: "2 weeks",

    /**
     * Exclude torrents which have been searched more recently than this long
     * ago.
     * Doesn't exclude previously failed searches.
     * Examples:
     * "2 days"
     * "5 days"
     *
     * This value must be 2-5x less than excludeOlder.
     */
    excludeRecentSearch: "3 days",

    /**
     * Which action to take upon a match being found.
     * Options: "save", "inject".
     */
    action: "save",

    /**
     * qBittorrent and Deluge specific.
     * Whether to inject using the same labels/categories as the original
     * torrent.
     *
     * qBittorrent: This will apply the category's original category as a tag.
     *
     * Example: if you have an original label/category called "Movies", this will
     * automatically inject cross-seeds to "Movies.cross-seed".
     */
    duplicateCategories: false,

    /**
     * Run rss scans on a schedule.
     * Set to undefined or null to disable. Minimum of 10 minutes.
     * Examples:
     * "10 minutes"
     * "1 hour"
     */
    rssCadence: undefined,

    /**
     * Run searches on a schedule.
     * Set to undefined or null to disable. Minimum of 1 day.
     * Examples:
     * "2 weeks"
     * "3 days"
     *
     * This value must be at least 3x less than your excludeRecentSearch
     */
    searchCadence: undefined,

    /**
     * Fail snatch requests that haven't responded after this long.
     * Set to null for an infinite timeout.
     * Examples:
     * "30 seconds"
     * null
     */
    snatchTimeout: "30 seconds",

    /**
     * Fail search requests that haven't responded after this long.
     * Set to null for an infinite timeout.
     * Examples:
     * "30 seconds"
     * null
     */
    searchTimeout: "2 minutes",

    /**
     * The number of searches to make in one run/batch.
     * If more than this many searches are queued,
     * "searchCadence" will determine how long until the next batch.
     *
     * Combine this with "excludeRecentSearch" and "searchCadence" to smooth
     * long-term API usage patterns.
     *
     * Set to null for no limit.
     */
    searchLimit: 100,

    /**
     * The list of infohashes or strings which are contained in torrents that
     * you want to be excluded from cross-seed. This is the same format as
     * torznab, surround the entire set of quoted strings in square brackets
     * You can use any combination which must be entered on the one line.
     * Leave as undefined to disable.
     *
     * examples:
     *
     *    blockList: ["-excludedGroup", "-excludedGroup2"],
     *    blocklist: ["x265"],
     *    blocklist: ["Release.Name"],
     *    blocklist: ["3317e6485454354751555555366a8308c1e92093"],
     */
    blockList: undefined,
};
//# sourceMappingURL=config.template.docker.cjs.map
```

### verbose logs

```
2025-01-21 14:42:54 info: cross-seed v6.9.1
2025-01-21 14:42:54 info: Validating your configuration...
2025-01-21 14:42:54 warn: outputDir should only contain .torrent files, cross-seed will populate and manage (https://www.cross-seed.org/docs/basics/options#outputdir)
2025-01-21 14:42:54 warn: Indexer http://192.168.155.88:9696/44/api was rate limited when fetching caps
2025-01-21 14:42:54 debug: Response body first 1000 characters: <?xml version="1.0" encoding="UTF-8"?>
<error code="429" description="Indexer is disabled till 01/22/2025 04:25:12 due to recent failures." />
2025-01-21 14:42:54 warn: Indexer http://192.168.155.88:9696/67/api was rate limited when fetching caps
2025-01-21 14:42:54 debug: Response body first 1000 characters: <?xml version="1.0" encoding="UTF-8"?>
<error code="429" description="Indexer is disabled till 01/21/2025 11:30:42 due to recent failures." />
2025-01-21 14:42:54 error: Indexer http://192.168.155.88:9696/51/api responded with code 404 when fetching caps, check verbose logs
2025-01-21 14:42:54 debug: Response body first 1000 characters: {
  "message": "IndexerDefinition with ID 51 does not exist",
  "description": "NzbDrone.Core.Datastore.ModelNotFoundException: IndexerDefinition with ID 51 does not exist\n   at NzbDrone.Core.Datastore.BasicRepository\u00601.Get(Int32 id) in ./Prowlarr.Core/Datastore/BasicRepository.cs:line 104\n   at NzbDrone.Core.Indexers.IndexerFactory.Get(Int32 id) in ./Prowlarr.Core/Indexers/IndexerFactory.cs:line 83\n   at NzbDrone.Api.V1.Indexers.NewznabController.GetNewznabResponse(Int32 id, NewznabRequest request) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 117\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Awaited|12_0(ControllerActionInvoker invoker, ValueTask\u00601 actionResultValueTask)\n   at Microsoft.AspNetCor
2025-01-21 14:42:54 verbose: [configdump] {
  delay: 30,
  torznab: [
    'http://192.168.155.88:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?apikey=[REDACTED]&t=search&cat=&q=',
    'http://192.168.155.88:9696/82/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/31/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/61/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/65/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/43/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/33/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/21/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/71/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/24/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/68/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/45/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/63/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/66/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/73/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/53/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/44/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/78/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/60/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/34/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/64/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/54/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/81/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/48/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/67/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/56/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/57/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/72/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/62/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/79/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/51/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/25/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/32/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/76/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/47/api?apikey=[REDACTED]',
    'http://192.168.155.88:9696/26/api?apikey=[REDACTED]'
  ],
  useClientTorrents: false,
  dataDirs: [],
  matchMode: 'safe',
  skipRecheck: true,
  autoResumeMaxDownload: 52428800,
  linkCategory: 'cross-seed-link',
  linkDirs: [],
  linkType: 'symlink',
  flatLinking: false,
  maxDataDepth: 2,
  torrentDir: '/torrents',
  outputDir: '/cross-seeds',
  includeSingleEpisodes: false,
  includeNonVideos: false,
  fuzzySizeThreshold: 0.02,
  seasonFromEpisodes: null,
  excludeOlder: 1209600000,
  excludeRecentSearch: 259200000,
  action: 'save',
  duplicateCategories: false,
  notificationWebhookUrls: [],
  port: 2468,
  snatchTimeout: 30000,
  searchTimeout: 120000,
  searchLimit: 100,
  verbose: false,
  blockList: [],
  apiKey: [REDACTED],
  radarr: [
    'http://192.168.155.88:7878/?apikey=[REDACTED]'
  ],
  sonarr: [
    'http://192.168.155.88:8989/?apikey=[REDACTED]'
  ]
}
2025-01-21 14:42:54 info: Your configuration is valid!
2025-01-21 14:42:54 info: Indexing torrentDir for reverse lookup...
2025-01-21 14:42:54 verbose: Indexing failed (2): Cannot read properties of null (reading 'getAllDownloadDirs')
2025-01-21 14:42:54 debug: Cannot read properties of null (reading 'getAllDownloadDirs')
TypeError: Cannot read properties of null (reading 'getAllDownloadDirs')
    at indexTorrents (file:///usr/src/cross-seed/dist/torrent.js:225:48)
    at async Promise.all (index 0)
    at async withMutex.useQueue (file:///usr/src/cross-seed/dist/torrent.js:308:17)
    at async file:///usr/src/cross-seed/dist/utils.js:406:20
    at async Command.<anonymous> (file:///usr/src/cross-seed/dist/cmd.js:225:9)
    at async Command.parseAsync (/usr/src/cross-seed/node_modules/commander/lib/command.js:923:5)
    at async file:///usr/src/cross-seed/dist/cmd.js:316:1
2025-01-21 14:42:54 info: Indexing torrentDir for reverse lookup...
2025-01-21 14:42:54 verbose: Indexing failed (1): Cannot read properties of null (reading 'getAllDownloadDirs')
2025-01-21 14:42:54 debug: Cannot read properties of null (reading 'getAllDownloadDirs')
TypeError: Cannot read properties of null (reading 'getAllDownloadDirs')
    at indexTorrents (file:///usr/src/cross-seed/dist/torrent.js:225:48)
    at async Promise.all (index 0)
    at async withMutex.useQueue (file:///usr/src/cross-seed/dist/torrent.js:308:17)
    at async file:///usr/src/cross-seed/dist/utils.js:406:20
    at async Command.<anonymous> (file:///usr/src/cross-seed/dist/cmd.js:225:9)
    at async Command.parseAsync (/usr/src/cross-seed/node_modules/commander/lib/command.js:923:5)
    at async file:///usr/src/cross-seed/dist/cmd.js:316:1
2025-01-21 14:42:54 info: Indexing torrentDir for reverse lookup...
2025-01-21 14:42:54 error: Indexing failed (0): Cannot read properties of null (reading 'getAllDownloadDirs')
```

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [x] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

### PR DESCRIPTION
**Pull request by ShanaryS**
Fixes #890

The refactoring of how torrents are indexed broke this use case since it wasn't explicitly defined. I verified this configuration and there should be no issues.

I also added an extra config check for `action: save` with linkDirs defined.

### CODE REVIEW

File: src/configSchema.ts [hunk 1]
```diff
@@ -501,6 +501,14 @@ export const VALIDATION_SCHEMA = z
...
 		ZodErrorMessages.seasonFromEpisodesMin,
 	)
+	.refine((config) => {
+		if (config.action === Action.SAVE && config.linkDirs.length) {
+			logger.error(
+				`You cannot use action 'save' with linkDirs, use 'inject' for cross-seed to perform linking.`,
+			);
+		}
+		return true;
+	})
```
Comment (mmgoodnow) [inline src/configSchema.ts:511]: I still think we should allow this.

Comment (ShanaryS) [reply src/configSchema.ts:511]: This won't fail, but an error is logged since linkDirs is misleading.

Comment (mmgoodnow) [reply src/configSchema.ts:511]: wow I'm not reading today

**Review by mmgoodnow — APPROVED** [review]
